# SPDX-FileCopyrightText: Copyright © 2020-2024, 2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

# WARNING: this file was generated from {{ yadm.source }}
# shellcheck shell=sh

path_prepend() {
  case ":$PATH:" in
    *":$1:"*) : ;;              # already present, do nothing
    *) PATH="$1:$PATH" ;;
  esac
}

path_append() {
  case ":$PATH:" in
    *":$1:"*) : ;;
    *) PATH="$PATH:$1" ;;
  esac
}

export GITHUB_COPILOT_TOKEN=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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
path_prepend "${ASDF_DATA_DIR:-$HOME/.asdf}/shims"
path_append "$HOME/.local/share/JetBrains/Toolbox/scripts"
export PATH

