# SPDX-FileCopyrightText: Copyright © 2020 - 2024 Caleb Cushing
#
# SPDX-License-Identifier: MIT

# WARNING: this file was generated from {{ yadm.source }}
# shellcheck shell=sh

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less --chop-long-lines'
export LESS='-R --quit-if-one-screen --silent'
export GPG_TTY=$(tty)
