# WARNING: this file was generated from {{ yadm.source }}
source <(curl --silent --location init.zshell.dev); zzinit

{% include "../extra/zshrc.os.{{ yadm.os }},e.zsh" %}
zi for z-shell/z-a-meta-plugins z-shell/H-S-MW

zi snippet OMZL::history.zsh

zi wait for \
  OMZL::theme-and-appearance.zsh atload"unalias ls" \
  OMZP::colored-man-pages \
  OMZP::systemd \
  OMZP::gitignore

{% include "../extra/rc.sh" %}
{% include "../extra/alias.zsh" %}

zi wait atload'. ~/.asdf/plugins/java/set-java-home.zsh' for z-shell/null

zstyle :plugin:history-search-multi-word reset-prompt-protect 1

eval "$(starship init zsh)"

schedprompt() {
  zle && zle reset-prompt
  sched +1 schedprompt
}

zmodload -i zsh/sched
schedprompt

zi wait for @zsh-users+fast

setopt GLOBDOTS
set -o emacs
bindkey "^R" history-search-multi-word
