# SPDX-FileCopyrightText: Copyright © 2020 - 2025 Caleb Cushing
#
# SPDX-License-Identifier: MIT

# WARNING: this file was generated from {{ yadm.source }}

emulate -L zsh
setopt extendedglob no_beep

# ------------------------------------------------------------
# Antidote
# ------------------------------------------------------------
ANTIDOTE_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/antidote"
ANTIDOTE_HOME="/usr/share/zsh-antidote"

if [[ -r "$ANTIDOTE_HOME/antidote.zsh" ]]; then
  source "$ANTIDOTE_HOME/antidote.zsh"
  antidote load "$ANTIDOTE_CONFIG_HOME/plugins.txt"
fi

# ------------------------------------------------------------
# Options / keybindings
# ------------------------------------------------------------
setopt GLOBDOTS
set -o emacs
bindkey "^R" history-search-multi-word

zstyle :plugin:history-search-multi-word reset-prompt-protect 1

# ------------------------------------------------------------
# Helpers
# ------------------------------------------------------------
has() { command -v "$1" >/dev/null 2>&1 }

# ------------------------------------------------------------
# Aliases (deterministic, no scheduler)
# ------------------------------------------------------------
has nvim        && alias vi="nvim"
has nvim        && alias vim="nvim -Xp"
has journalctl  && alias journalctl="journalctl --output cat --boot 0 --full"
has dmesg       && alias dmesg="dmesg --color=always | less"
has lsblk       && alias lsblk="lsblk -o name,label,fstype,uuid"
has pbcopy      && alias clip="pbcopy"
has xclip       && alias clip="xclip -selection clipboard -in"
has bat         && alias cat="bat --plain --plain"
has eza         && alias ls="eza"
has plocate     && alias locate="plocate"
has dust        && alias du="dust"
has kalker      && alias bc="kalker"
has procs       && alias ps="procs"
has tokei       && alias cloc="tokei"

# ------------------------------------------------------------
# Tool hooks
# ------------------------------------------------------------
has zoxide && eval "$(zoxide init zsh --cmd c)"
has direnv && eval "$(direnv hook zsh)"
has kubectl && eval "$(kubectl completion zsh)"

# ------------------------------------------------------------
# Language / SDK paths
# ------------------------------------------------------------
has cargo && export PATH="$PATH:$HOME/.cargo/bin"

if has asdf; then
  [[ -r ~/.asdf/plugins/java/set-java-home.zsh ]] &&
    source ~/.asdf/plugins/java/set-java-home.zsh
  [[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc" ]] &&
    source "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc"
fi


# ------------------------------------------------------------
# Prompt
# ------------------------------------------------------------
has starship && eval "$(starship init zsh)"
