#!/bin/sh
set -x
if command -v zsh >/dev/null 2>&1; then 
  if [ ! -d "$HOME/.oh-my-zsh" ]; then
    curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh > /tmp/install.sh
    chmod +x /tmp/install.sh
    /tmp/install.sh --keep-zshrc
    curl -fsSL https://raw.githubusercontent.com/reobin/typewritten/master/typewritten.zsh-theme > "$HOME/.oh-my-zsh/custom/themes/typewritten.zsh-theme"
  fi
fi
