#!/bin/sh
set -x
if command -v zsh >/dev/null 2>&1; then 
  if [ ! -d "$HOME/.oh-my-zsh" ]; then
    export KEEP_ZSHRC=1
    eval "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    curl -fsSL https://raw.githubusercontent.com/reobin/typewritten/master/typewritten.zsh-theme > "$HOME/.oh-my-zsh/custom/themes/typewritten.zsh-theme"
  fi
fi
