#!/bin/sh
set -x

DOWNLOAD_DIR=$(xdg-user-dir DOWNLOAD)
WGET="wget --no-verbose --timestamping --directory-prefix $DOWNLOAD_DIR"
WGET_GH='wget --no-verbose --no-if-modified-since'
TAR='tar --extract --verbose --keep-newer-files --file'
SCRIPTDIR="$(dirname $0)/bootstrap.d"
if readlink -e "$SCRIPTDIR"; then
  for f in $SCRIPTDIR/*.sh; do source $f; done
fi

mkdir -p ~/.local/bin

if command -v zsh >/dev/null 2>&1; then
  set +x
  $WGET_GH --output-document - https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh > /dev/null | sh
  set -x
fi


if command -v vim >/dev/null 2&>1; then
  VIM_COLORDIR="$HOME/.vim/colors"
  VIM_PLUGDIR="$HOME/.vim/pack/local/start"
  VIM_AFTER_SYNTAX="$HOME/.vim/after/syntax"
  VIM_EDITORCONFIG="editorconfig-vim"
  VIM_EDITORCONFIG_URI="https://github.com/editorconfig/$VIM_EDITORCONFIG.git"

  mkdir -p $VIM_PLUGDIR
  mkdir -p $VIM_AFTER_SYNTAX
  if [ ! -d "$VIM_PLUGDIR/$VIM_EDITORCONFIG" ]; then
    git clone --quiet $VIM_EDITORCONFIG_URI "$VIM_PLUGDIR/$VIM_EDITORCONFIG"
  else
    git -C "$VIM_PLUGDIR/$VIM_EDITORCONFIG" pull "$VIM_EDITORCONFIG_URI"
  fi
  $WGET_GH --directory-prefix $VIM_COLORDIR https://raw.githubusercontent.com/toupeira/vim-desertink/master/colors/desertink.vim
  $WGET_GH --directory-prefix $VIM_AFTER_SYNTAX https://raw.githubusercontent.com/zinit-zsh/zinit-vim-syntax/master/after/syntax/zsh.vim
fi

TOOLBOX_VERSION=1.20.7940
$WGET https://download-cf.jetbrains.com/toolbox/jetbrains-toolbox-$TOOLBOX_VERSION.tar.gz \
  && $TAR $DOWNLOAD_DIR/jetbrains-toolbox-$TOOLBOX_VERSION.tar.gz --strip-components=1 -C ~/.local/bin

