#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/xeno/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
dunst &
cbatticon &
albert &
konversation &
discord &
slack --silent &
opera &
alacritty &
~/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox &
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox -log ~/.cache/fluxbox/log
# or if you want to keep a log:
# exec fluxbox -log "/home/xeno/.fluxbox/log"
