#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [[ -f /opt/asdf-vm/asdf.sh ]]; then
  . /opt/asdf-vm/asdf.sh
  . ~/.asdf/plugins/java/set-java-home.bash
  ./gradlew spotlessApply
fi
git add -u
yarn lint-staged
