#!/bin/sh

pamac install --no-confirm \
   acpi \
   aspell-en \
   awesome-terminal-fonts \
   b43-fwcutter \
   bitwarden \
   bitwarden-cli \
   bluez-utils \
   breeze-maia-icon-themes \
   btrfsmaintenance \
   chromium \
   cronie \
   diff-so-fancy \
   discord \
   docker \
   dust \
   ecryptfs-utils \
   efibootmgr \
   exfat-utils \
   fd \
   fio \
   flex \
   gdm-plymouth \
   gparted \
   gpg-tui \
   gthumb \
   gucharmap \
   gufw \
   hexchat \
   htop \
   hugo \
   hyperfine \
   i2c-tools \
   inetutils \
   inkscape \
   intel-ucode \
   iotop \
   iputils \
   jpegoptim \
   jq \
   kde-gtk-config \
   kernel-alive \
   lib32-mesa-demos \
   licenses \
   linux60 \
   lollypop \
   lsd \
   man-pages \
   manjaro-alsa \
   manjaro-artwork \
   manjaro-aur-support \
   manjaro-dynamic-wallpaper \
   manjaro-gnome-postinstall \
   manjaro-hotfixes \
   manjaro-log-helper \
   manjaro-pipewire \
   manjaro-printer \
   manjaro-ranger-settings \
   manjaro-release \
   manjaro-system \
   manjaro-zsh-config \
   mc \
   mdns-scan \
   memtest86+ \
   mkinitcpio-openswap \
   mousetweaks \
   mtr \
   nano \
   nautilus-admin \
   nautilus-empty-file \
   ncompress \
   ndisc6 \
   netctl \
   nfs-utils \
   nmap \
   ntp \
   numlockx \
   nvme-cli \
   opera \
   os-prober \
   otf-fira-mono \
   otf-fira-sans \
   parallel \
   pkgconf \
   plymouth-theme-manjaro \
   plymouth-theme-manjaro-elegant-hidpi \
   plymouth-theme-manjaro-gnome \
   polkit-gnome \
   procs \
   pulseaudio-ctl \
   sdparm \
   signal-desktop \
   snapper \
   spectre-meltdown-checker \
   systemd-boot-manager \
   systemd-fsck-silent \
   telegram-desktop \
   tokei \
   traceroute \
   transmission-gtk \
   ttf-fira-code \
   ttf-inconsolata \
   ttf-indic-otf \
   vi \
   vim-spell-en \
   webapp-manager \
   whois \
   xdg-user-dirs-gtk \
   xf86-input-evdev \
   xf86-video-intel \
   xf86-video-nouveau \
   xorg-mkfontscale \
   xorg-xev \
   xorg-xinit \
   yadm \
   zoxide \
   zram-generator \
   ananicy \
   asdf-vm \
   atool \
   brix-git \
   deb2targz \
   direnv \
   dropbox \
   em-keyboard \
   fontfor \
   gconf \
   git-spindle \
   jetbrains-toolbox \
   kalker \
   otf-symbola \
   slack-desktop \
   speedtest-netperf \
   tcptraceroute \
   teams \
   transfersh \
   wev \
   zoom \
   bfg \
   github-cli
