name: Full Unoptimized Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_call:
jobs:
  full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true
      - run: ./gradlew build --no-build-cache --no-configuration-cache
